language: node_js
dist: xenial
node_js:
  - "lts/*"
python: 3.6
cache: npm
before_install:
  - sudo apt-get install -y libchromaprint-tools python3-setuptools python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install python-magic pathlib eyeD3
  - eyeD3 --version
services:
  - redis-server
addons:
  apt:
    update: true
  mariadb: '10.3'
before_script:
  - mysql -u root -e "CREATE DATABASE mp3manager_test CHARACTER SET = 'utf8' COLLATE = 'utf8_general_ci';"
  - mysql -u root -e "CREATE USER 'mp3admin_test'@'127.0.0.1' IDENTIFIED BY 'musictest';"
  - mysql -u root -e "GRANT ALL ON mp3manager_test.* TO 'mp3admin_test'@'127.0.0.1';"
  - mysql -u root -e "CREATE USER 'mp3admin_test'@'localhost' IDENTIFIED BY 'musictest';"
  - mysql -u root -e "GRANT ALL ON mp3manager_test.* TO 'mp3admin_test'@'localhost';"
install:
  - npm install -g lerna
  - lerna bootstrap --hoist
