language: node_js
dist: xenial
node_js:
  - "lts/*"
before_install:
  - sudo apt-get install -y libchromaprint-tools
addons:
  apt:
    update: true
install:
  - npm install -g lerna
  - lerna bootstrap --hoist
